openai_api_key: sk-proj-NlX..

# modelos
# gpt-3.5-turbo	-- simples, barato e rápido
# gpt-4 -- mais caro e mais preciso
# gpt-4-turbo -- mais poderoso
# gpt-4o --multi-modal, mais poderoso

modelos:
  independentes:
      # multi-modal!
      analisar_previsao: gpt-4o
      # multi-modal!      
      analisar_tecnico: gpt-4o
      analisar_fundamentalista: gpt-4       
      analisar_noticias: gpt-4      
  avaliadores:
      avaliador_1: gpt-4-turbo
      avaliador_2: gpt-4-turbo

prompts:
  independentes:
    analisar_previsao: >
      Analise o gráfico de previsão de preços e diga se a tendência
      é positiva, negativa ou neutra. Justifique em até 250 palavras.
    analisar_tecnico: >
      Com base no gráfico técnico (RSI/MACD/MME), diga se a recomendação
      seria compra, venda ou manutenção. Explique brevemente.
    analisar_noticias: >
      Analise o sentimento das notícias a seguir (positivo, negativo ou neutro)
      e forneça uma justificativa resumida.
    analisar_fundamentalista: >
      Com base exclusivamente nos dados contábeis fornecidos abaixo, 
      extraídos das demonstrações financeiras da empresa, avalie a situação econômico-financeira atual. 
      Aponte os principais pontos fortes, fraquezas e riscos percebidos. Responda com clareza e objetividade. 
      Limite sua análise a no máximo 200 palavras.

      
  avaliadores:
    avaliador_1: >
      Você é um avaliador imparcial. Leia os pareceres dos especialistas e
      forneça uma recomendação final: COMPRAR, VENDER ou ESPERAR.
      Justifique em até 250 palavras.
    avaliador_2: >
      Com base nas análises a seguir dos agentes de previsão, técnico e
      notícias, forneça um parecer final objetivo: COMPRAR, VENDER ou ESPERAR.
      Inclua uma justificativa coerente e concisa.

noticias:
  termos:
    - ações
    - balanço
    - lucro
    - prejuízo
    - resultados
    - financeiro
    - investidores

  fontes:
    - valor.globo.com
    - exame.com
    - infomoney.com.br
    - braziljournal.com
    - investing.com
    - forbes.com.br
    - b3.com.br
    - estadao.com.br

  maximo_resultados: 5
